### ISSUE TITLE
Soft new lines (br tags) are not being being properly processed

### ISSUE THREAD

**Issue by jdiprizio** [sstur/draft-js-import-element#1]
When converting HTML to Draft content fragments, br tags are not properly converted back to Draft soft newlines '\n' characters (as can be seen in [Draft's RichTextUtil insertSoftNewline method](https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L81)).

You can actually witness this issue in your [React RTE demo](https://react-rte.org/demo) by adding some content with soft newlines, then copying the HTML code and pasting it back in the Editor Source field.

I haven't quite grasped the rationale in your code to use '\r' for br tags but anyway these '\r' characters are getting stripped in your [collapseWhiteSpace method](https://github.com/sstur/draft-js-import-element/blob/master/src/stateFromElement.js#L305).

Right now my quick and dirty fix is to use '\n' for br tags and removing '\n' from your collapseWhiteSpace regex but  have a feeling that's not the way to go. If you don't mind sharing a bit more about the whole '\r' rationale I'd be more than happy to do a proper pull request with the correct fix.

**Comment by sstur** [comment]
Hi @jdiprizio. Thanks for finding this bug. You are most certainly correct that this behavior needs a fix. Will figure this out and update here.
