### ISSUE TITLE
can't handle <img> tag

### ISSUE THREAD

**Issue by DerekHung** [sstur/draft-js-import-element#11]
Hello,

I've tried to transform html content to contentState

Everything goes fine but <img>

The output result shows there's not any image element but only '~' string

Would you take a look and fix it?  

Thanks a lot!

**Comment by cismous** [comment]
+1

**Comment by sergiodxa** [comment]
It works if you wrap the `<img />` into a `<figure>`. I think there should be a way to use just `<img />` without a `<figure>`

**Comment by sstur** [comment]
I'm not entirely sure what the expected behavior is when encountering an `<img>`.

**Comment by svnm** [comment]
@sergiodxa How did you get it to work by wrapping it in a `<figure>` element. It didn't work for me.

None of these work for me:

```jsx
let html = '<figure><img src="img/pic.png"></figure>'
html = '<div><img src="x.png" /></div>'
html = '<img src="x.png" />'
let contentState = stateFromHTML(html)
let editorState = EditorState.createWithContent(contentState)
```

**Comment by ErickVoodoo** [comment]
Up
