### ISSUE TITLE
Element class

### ISSUE THREAD

**Issue by mitfity** [sstur/draft-js-import-element#18]
Is there a way to somehow pass html element css class to block? Maybe through block data. 
So is there a way to pass custom block data? I saw you have blockrenderers option for '**draft-js-export-element**' but didn't see any chance to pass something like that to options.
Draft.js has **blockStyleFn** as you know and it would be great to have block class passed with block data so you can get it within this function with block.getData().
https://facebook.github.io/draft-js/docs/advanced-topics-block-styling.html#content
Sorry if it is mean (my English is not ideal) or smth, I am struggling with this whole day now and probably I will have to do some tricks to pass class with block and then catch ContentState this plugin generates and move those classes to block data.
**BTW inline styles also disappear or is it problem in my code?**

**Comment by anztrax** [comment]
i need that option too :), support custom style

**Comment by skolmer** [comment]
@mitfity @anztrax  I have created a PR (#25) that imports class attributes as block data. This allows you to keep your custom css classes on block elements. You could use for example a blockStyleFn like this:

``` js
function myBlockStyleFn(contentBlock) {
  const data = contentBlock.getData();
  return data['class'];
}
```

**Comment by sstur** [comment]
This is now supported using `customBlockFn` in v0.4.3.

**Comment by anztrax** [comment]
thanks @sstur :+1:
