### ISSUE TITLE
Return inline elements before to block elements

### ISSUE THREAD

**Issue by jhta** [sstur/draft-js-import-element#22]
When I tried of  import html with `h2`, `h3`, `img` and other tags, it's inserting the inline elements `a`, `strong` before

For example, innsert the text before the title

**Comment by svnm** [comment]
I also have this issue. 
Given this string:
```jsx
<div>
  <p>xx</p>
  <img src="react.png" />
  <p>yy</p>
</div>
```

I get back:

```jsx
<p><img src="react.png" /></p>
<p>xx</p>
<p>yy</p>
```

**Comment by svnm** [comment]
It looks like it works fine if I wrap them in a block element e.g. So that is one possible fix if anyone runs into this issue

```jsx
<div>
  <p>xx</p>
  <div><img src="react.png" /></div>
  <p>yy</p>
</div>
```
