### ISSUE TITLE
Any way to inject ELEM_ATTR_MAP?

### ISSUE THREAD

**Issue by afhole** [sstur/draft-js-import-element#23]
Is there any way to have a user-definable ELEM_ATTR_MAP?
I'd like to add some arbitrary `data-*` attributes  to incoming `a` tags (and then export them again with your export library) but I'm not sure if that's currently possible?

**Comment by afhole** [comment]
Looking at the code it seems this is only necessary to map attributes to different names, and anything else is just pulled through like for like, so this may be a non-issue

**Comment by afhole** [comment]
Yes, I see that attributes flow in and out nicely (well, `data-` attribs at least). Closing!

**Comment by rpmonteiro** [comment]
Hey @afhole , I'm trying to achieve the same thing but I'm finding it very difficult. Would you mind just posting a little snippet on how you did it? 
Cheers

**Comment by afhole** [comment]
Hi @rpmonteiro - basically I realised that I don't need to inject a ELEM_ATTR_MAP - draft-js-import-element will now mirror any attributes you add to the entity, e.g.

```
Entity.create('LINK', 'MUTABLE', {
    url: 'http://example.com',
    target: '_blank',
    'data-some-custom-attribute': '123'
});
```

I think this was added a few releases after I first started using the library so at first I hadn't realised that was possible. The only gotcha is to remember that draft maps url > href and vice versa but everything else is 1:1 mapping with draft-js-import-element. Hope that helps :)

**Comment by rpmonteiro** [comment]
To be honest I still don't get it, but your help was very much appreciated. I might come back to this in a couple days and be like 'this was so simple'. Cheers

**Comment by afhole** [comment]
Essentially if you are already creating link entities like here https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#creating-and-retrieving-entities then you can just add whatever attributes you like alongside `href` - obviously just make sure anything with a dash is quoted, e.g. `{'data-my-attribute': '123'}`

**Comment by eessex** [comment]
I would also like to import a custom ELEM_ATTR_MAP, specifically to add classes to Link elements -- class does not seem to map onto the entity when created.  Is there a way to pass this into options?
