### ISSUE TITLE
Warning: DraftEntity.create will be deprecated soon. Please use "contentState.createEntity" instead.

### ISSUE THREAD

**Issue by goodhyun** [sstur/draft-js-import-element#31]
You can see the following warning, if you are using the upcoming 0.10.0 draft-js

```
WARNING: DraftEntity.create will be deprecated soon!
Please use "contentState.createEntity" instead.
```

The culprit was around here: 

`      return Entity.create(ENTITY_TYPE.LINK, 'MUTABLE', data);
`

**Comment by gbbr** [comment]
This could deem to be tricky since an array of blocks is generated, which is later used to return a content state. At the point where the entity is created there is technically no content state available. It'd be nice to fix this.

**Comment by poci-hu** [comment]
+1, what if we don't have a contentState (yet)?
