### ISSUE TITLE
customInlineFn?

### ISSUE THREAD

**Issue by toblix** [sstur/draft-js-import-element#32]
In order to be able to style exported HTML through CSS, I've exported some custom inline styles as HTML classes, so there's a bunch of `<span class="special"/>` elements in my exported HTML (using `inlineStyles` in *draft-js-export-html*). This works fine, but there doesn't appear to be a way to do the transformation in reverse, as only blocks get the custom treatment through `customBlockFn`, and the only inline transformation configuration supported in *draft-js-import-element* is `elementStyles`, which maps directly from tag name.

Would it be possible to expose a function that, say, lets you push styles on the stack based on the element?

**Comment by sstur** [comment]
Taking a different approach to customizing inline elements. Subscribe to the [new repo](https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-import-element) for updates.

**Comment by sstur** [comment]
Hi @toblix.
Agreed, we need to satisfy this use case. I'm working with @smvilar on a solution which you can track [here](https://github.com/sstur/draft-js-utils/pull/91).
