### ISSUE TITLE
customBlockFn can't get span

### ISSUE THREAD

**Issue by PrimeObjects** [sstur/draft-js-import-element#33]
Hello, 
I have a html 
`<p><span style='color: #FF0000'></span><p>` , but the color style of span could not be seen in editor.

try to use the option and it did not catch SPAN
```
const options = {
                 customBlockFn(element) {
                    let { tagName, style } = element;
                    if (tagName === 'SPAN' && style.color) {
                        return { data: { color: style.color } };
                    }
                }
            }
```

Or can we have something like you did in https://github.com/sstur/draft-js-export-html

let options = { inlineStyles: {RED: {style: {color: '#FF0000'}}} ?

Thanks lot
Gary

**Comment by sstur** [comment]
Currently this is not supported, but we're working on a solution that can handle inline elements in a custom way.

**Comment by sstur** [comment]
@PrimeObjects: we're working on a solution for this which is tracked [here](https://github.com/sstur/draft-js-utils/pull/91).
