### ISSUE TITLE
Soft returns are suffixed with a space

### ISSUE THREAD

**Issue by afhole** [sstur/draft-js-import-element#5]
When importing soft returns e.g. `<br>\n` a space is added after the line break, effectively prefixing subsequent lines with a single space

**Comment by sstur** [comment]
Oh, I totally know what's causing this. There's even a friggin todo in the source:

https://github.com/sstur/draft-js-import-element/blob/0deef116e34e1ffa3a7951ccf7ac23856f750572/src/stateFromElement.js#L155

I'll try to get a fix out soon.

**Comment by afhole** [comment]
Awesome, thanks. I started having a look at a fix but wasn't sure of the best way to go about it.
If you can point me in the right direction I will try and fix and raise a PR, otherwise I will leave it to you.
Cheers

**Comment by sstur** [comment]
There's not a super easy fix. The naive solution that comes to mind is to do a search and replace, but remember that modifying the content string in any way must make corresponding changes to the character meta data (style and entity) so it gets tricky.

I guess we could split on soft breaks and then use trimLeadingSpace/trimTrailingSpace for each part but I expect there is a better way (perhaps during the collapse white space part).

I'll have to take a closer look.

**Comment by sstur** [comment]
I've created #6 which seems to do the job well, but there's a lot of code there just to search & replace `\n` followed by a space.

I'm curious if you have any thoughts before I land this.

**Comment by afhole** [comment]
Honestly I don't feel knowledgable enough with draft.js right now to be able to comment meaningfully (and regrettably don't have the time to reach that stage yet). I'm happy to test this also if you like otherwise I would say go ahead an merge it.
